In [5]:
import numpy as py

### Array created

In [6]:
a = py.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


### Array by arange

In [ ]:
arr_table = py.arange(10000) * 2
print(arr_table)

[    0     2     4 ... 19994 19996 19998]


In [17]:
arr_zero = py.zeros(3)
print(arr_zero)

arr_ones = py.ones(3)
print(arr_ones)

[0. 0. 0.]
[1. 1. 1.]


In [19]:
arr = py.array([[1,2,3,4] , [5,6,7,8]])

print(arr.size)
print(arr.shape)

8
(2, 4)


## Transpose of matrices

In [24]:
arr1 = py.array([[1,2,3] , [4,5,6]])
print(arr1.flatten())
print(arr1.T)

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
