In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3,4] , [5,6,7,8]])
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
int64
2


In [4]:
arr1 = np.array([[1,4,3] , [4,5,1]])
print(np.sort(  arr1, axis=0))
print(np.sort(arr1))

[[1 4 1]
 [4 5 3]]
[[1 3 4]
 [1 4 5]]


In [6]:
arr11 = np.where(arr1 > 3)
print(arr11)
print(arr1[arr11])


(array([0, 1, 1]), array([1, 0, 1]))
[4 4 5]


In [10]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])

In [11]:

print(a.shape == b.shape)

True


In [14]:
dell = np.delete(a, 2)
print(dell)

[1 2 4 5]
